/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AffiliateProduct {
  'url' : string,
  'name' : string,
  'description' : string,
  'productId' : bigint,
  'discount' : string,
  'price' : string,
}
export interface BlogPost {
  'title' : string,
  'content' : string,
  'author' : string,
  'timestamp' : Time,
  'excerpt' : string,
  'category' : string,
  'postId' : bigint,
}
export interface Feedback {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'feedbackId' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addAffiliateProduct' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'createBlogPost' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'getAffiliateProduct' : ActorMethod<[bigint], AffiliateProduct>,
  'getAllAffiliateProducts' : ActorMethod<[], Array<AffiliateProduct>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllFeedbackEntries' : ActorMethod<[], Array<Feedback>>,
  'getBlogPost' : ActorMethod<[bigint], BlogPost>,
  'submitFeedback' : ActorMethod<[string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];