/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AffiliateProduct = IDL.Record({
  'url' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productId' : IDL.Nat,
  'discount' : IDL.Text,
  'price' : IDL.Text,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
  'postId' : IDL.Nat,
});
export const Feedback = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'feedbackId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAffiliateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAffiliateProduct' : IDL.Func([IDL.Nat], [AffiliateProduct], ['query']),
  'getAllAffiliateProducts' : IDL.Func(
      [],
      [IDL.Vec(AffiliateProduct)],
      ['query'],
    ),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllFeedbackEntries' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AffiliateProduct = IDL.Record({
    'url' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productId' : IDL.Nat,
    'discount' : IDL.Text,
    'price' : IDL.Text,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
    'postId' : IDL.Nat,
  });
  const Feedback = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'feedbackId' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAffiliateProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAffiliateProduct' : IDL.Func([IDL.Nat], [AffiliateProduct], ['query']),
    'getAllAffiliateProducts' : IDL.Func(
        [],
        [IDL.Vec(AffiliateProduct)],
        ['query'],
      ),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllFeedbackEntries' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [BlogPost], ['query']),
    'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };